version: "3.5"

services:
  db:
    image: mysql:5.7.42
    environment:
      - MYSQL_DATABASE=one
      - MYSQL_USER=app
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_HOST=%
    # NOTE: use of "mysql_native_password" is not recommended:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # this is just an example, not intended to be a production configuration)
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    secrets:
      - mysql_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
secrets:
  mysql_password:
    file: ../password.txt

# https://hub.docker.com/_/mysql
# https://dev.mysql.com/doc/refman/5.7/en/docker-mysql-more-topics.html